<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260330125102 extends AbstractMigration
{
    private function isMySql(): bool
    {
        return 'mysql' === $this->connection->getDatabasePlatform()->getName();
    }

    private function isPostgreSql(): bool
    {
        return 'postgresql' === $this->connection->getDatabasePlatform()->getName();
    }

    public function getDescription(): string
    {
        return 'Create initial schema for users, events, registrations and consent logs';
    }

    public function up(Schema $schema): void
    {
        if ($this->isMySql()) {
            $this->addSql('CREATE TABLE consent_log (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(50) NOT NULL, timestamp DATETIME NOT NULL, ip_address VARCHAR(64) DEFAULT NULL, details VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_30113729A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
            $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, event_date DATETIME NOT NULL, location VARCHAR(255) NOT NULL, max_participants INT NOT NULL, is_published TINYINT NOT NULL, created_at DATETIME NOT NULL, organizer_id INT NOT NULL, INDEX IDX_3BAE0AA7876C4DDA (organizer_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
            $this->addSql('CREATE TABLE registration (id INT AUTO_INCREMENT NOT NULL, registered_at DATETIME NOT NULL, status VARCHAR(20) NOT NULL, user_id INT NOT NULL, event_id INT NOT NULL, INDEX IDX_62A8A7A7A76ED395 (user_id), INDEX IDX_62A8A7A771F7E88B (event_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
            $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, consent_date DATETIME DEFAULT NULL, consent_version VARCHAR(10) DEFAULT NULL, is_anonymized TINYINT NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
            $this->addSql('ALTER TABLE consent_log ADD CONSTRAINT FK_30113729A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
            $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7876C4DDA FOREIGN KEY (organizer_id) REFERENCES `user` (id)');
            $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A7A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
            $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A771F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');

            return;
        }

        if ($this->isPostgreSql()) {
            $this->addSql('CREATE TABLE consent_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(64) DEFAULT NULL, details VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_30113729A76ED395 ON consent_log (user_id)');
            $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organizer_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, event_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, max_participants INT NOT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_3BAE0AA7876C4DDA ON event (organizer_id)');
            $this->addSql('CREATE TABLE registration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, event_id INT NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_62A8A7A7A76ED395 ON registration (user_id)');
            $this->addSql('CREATE INDEX IDX_62A8A7A771F7E88B ON registration (event_id)');
            $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, consent_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, consent_version VARCHAR(10) DEFAULT NULL, is_anonymized BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
            $this->addSql('ALTER TABLE consent_log ADD CONSTRAINT FK_30113729A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7876C4DDA FOREIGN KEY (organizer_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A771F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported database platform: %s', $this->connection->getDatabasePlatform()->getName()));
    }

    public function down(Schema $schema): void
    {
        if ($this->isMySql()) {
            $this->addSql('ALTER TABLE consent_log DROP FOREIGN KEY FK_30113729A76ED395');
            $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7876C4DDA');
            $this->addSql('ALTER TABLE registration DROP FOREIGN KEY FK_62A8A7A7A76ED395');
            $this->addSql('ALTER TABLE registration DROP FOREIGN KEY FK_62A8A7A771F7E88B');
            $this->addSql('DROP TABLE consent_log');
            $this->addSql('DROP TABLE event');
            $this->addSql('DROP TABLE registration');
            $this->addSql('DROP TABLE `user`');

            return;
        }

        if ($this->isPostgreSql()) {
            $this->addSql('ALTER TABLE consent_log DROP CONSTRAINT FK_30113729A76ED395');
            $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7876C4DDA');
            $this->addSql('ALTER TABLE registration DROP CONSTRAINT FK_62A8A7A7A76ED395');
            $this->addSql('ALTER TABLE registration DROP CONSTRAINT FK_62A8A7A771F7E88B');
            $this->addSql('DROP TABLE consent_log');
            $this->addSql('DROP TABLE event');
            $this->addSql('DROP TABLE registration');
            $this->addSql('DROP TABLE "user"');

            return;
        }

        $this->abortIf(true, sprintf('Unsupported database platform: %s', $this->connection->getDatabasePlatform()->getName()));
    }
}
